CREATE DATABASE paperlessdb;
\c paperlessdb;

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    content BYTEA NOT NULL,  -- This is for binary content
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO documents (name, status, content)
VALUES ('Test Document', 'deactivated', decode('48656c6c6f2c20576f726c64', 'hex'));

