version: '3'
services:
  paperless-rest:
    build: .
    ports:
      - "8081:8080"
    container_name: dms-app-container

  paperless-broker:
    image: redis:6.0
    restart: unless-stopped

  paperless-db:
    build: paperless-db/.
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - paperless-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    ports:
      - "80:8000"
    restart: unless-stopped
    depends_on:
      - paperless-db
      - paperless-broker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /opt/docker-prod/paperless/data:/usr/src/paperless/data
      - /opt/docker-prod/paperless/media:/usr/src/paperless/media
      - paperless-db-data:/var/lib/postgresql/data
    environment:
      PAPERLESS_REDIS: redis://paperless-broker:6379
      PAPERLESS_DBHOST: paperless-db
      PAPERLESS_URL: http://localhost
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_TIME_ZONE: Europe/Berlin

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  spring-boot-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

volumes:
  paperless-db-data: