version: '3'
services:
  paperless-rest:
    build:
      context: ./paperless-rest
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    container_name: dms-app-container
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq # RabbitMQ hostname
      SPRING_RABBITMQ_PORT: 5672
      SPRING_DATASOURCE_URL: jdbc:postgresql://paperless-db:5432/paperless
      SPRING_DATASOURCE_USERNAME: paperless
      SPRING_DATASOURCE_PASSWORD: paperless
    depends_on:
      - paperless-db
      - rabbitmq

  paperless-worker:
    build:
      context: ./paperless-services
      dockerfile: Dockerfile
    container_name: paperless-worker-container
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: paperless
      SPRING_RABBITMQ_PASSWORD: paperless
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq

  paperless-db:
    build: paperless-db/.
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - paperless-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  paperless-ui:
    build:
      context: ./paperless-ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: paperless-ui-container

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq

volumes:
  paperless-db-data:
