version: '3'
services:
  paperless-rest:
    build:
      context: ./paperless-rest
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    container_name: dms-app-container

  paperless-db:
    build: paperless-db/.
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - paperless-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  paperless-ui:
    build:
      context: ./paperless-ui
      dockerfile: Dockerfile
    ports:
      - "80:80"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq

volumes:
  paperless-db-data: